name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      # ⬇️ Build sin tests
      - name: Build (skip tests)
        run: ./mvnw -B -DskipTests=true clean package

      # ⬇️ El .jar generado como artifact del run
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: task-movil-api-jar
          path: target/*.jar
